<?php

use Illuminate\Database\Seeder;

class PlateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $plates = [
            [
                'restaurant_id' => 1,
                'plate_name' => 'Cheese Burger',
                'description' => 'Due fette di formaggio americano Kraft fuso tra due polpette appena grigliate con pane morbido tostato.',
                'image' => '',
                'price' => 10,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 1,
                'plate_name' => 'Bacon Cheese Burger',
                'description' => 'Due polpette fatte a mano grigliate al momento - con due fette di bacon croccante e due fette di formaggio americano Kraft con pane morbido ai semi di sesamo.',
                'image' => '',
                'price' => 12,90,
                'visible' => '1',
                'popular' => '1',
            ],
            [
                'restaurant_id' => 1,
                'plate_name' => 'Cheese Veggie Sandwich',
                'description' => 'Cipolle, funghi e peperoni verdi grigliati con formaggio fuso americano Kraft servito su pane dorato e tostato con lattuga e pomodori. Più una delle tue 16 guarnizioni preferite!',
                'image' => '',
                'price' => 7,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 1,
                'plate_name' => 'Kosher Style Hot Dog',
                'description' => 'L’hot dog nazionale ebraico di sola carne di manzo è spaccato e grigliato longitudinalmente per un esterno caramellato.',
                'image' => '',
                'price' => 8,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 2,
                'plate_name' => 'Bowl Classic',
                'description' => 'riso, salmone, edamame, avocado, sesamo, alghe nori e salsa unaghi',
                'image' => '',
                'price' => 9,90,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 2,
                'plate_name' => 'Bowl Salmon Anaua',
                'description' => 'riso, salmone griglia, edamame, sesamo e salsa teriyaki',
                'image' => '',
                'price' => 11,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 2,
                'plate_name' => 'Bowl Tonno Hawa',
                'description' => 'riso, spicy tonno, jalapeño, avocado, cetrioli, carote, sesamo, tobiko e spicy maionese',
                'image' => '',
                'price' => 11,90,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 2,
                'plate_name' => 'Bowl White Fish',
                'description' => 'riso, spigola, mango, avocado, edamame, sesamo, alghe nori e ponzu',
                'image' => '',
                'price' => 10,90,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 3,
                'plate_name' => 'Riso Cantonese',
                'description' => 'Riso con prosciutto, piselli e frittata.',
                'image' => '',
                'price' => 4,20,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 3,
                'plate_name' => 'Noodles',
                'description' => 'Noodles di riso con mix di verdure & uovo (carote, zucchine,cavolo).',
                'image' => '',
                'price' => 5,20,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 3,
                'plate_name' => 'Ravioli di Manzo',
                'description' => 'Ravioli cotti al vapore farciti con mix di verdure e manzo.',
                'image' => '',
                'price' => 3,5,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 3,
                'plate_name' => 'Involini Primavera',
                'description' => 'Involtini fritti con ripieno di verdure miste, preparati a mano dai nostri cuochi il tutto accompagnato da salsa agrodolce a parte.',
                'image' => '',
                'price' => 3,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => '',
                'plate_name' => '',
                'description' => '',
                'image' => '',
                'price' => '',
                'visible' => '1',
                'popular' => '0',
            ],
        ];
    }
}
