<?php

use Illuminate\Database\Seeder;

class PlateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // array di piatti collegati con la foreign keys ad ogni ristorante
        $plates = [
            [
                'restaurant_id' => 1,
                'plate_name' => 'Cheese Burger',
                'description' => 'Due fette di formaggio americano Kraft fuso tra due polpette appena grigliate con pane morbido tostato.',
                'image' => 'cheeseburger.png',
                'price' => 10,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 1,
                'plate_name' => 'Bacon Cheese Burger',
                'description' => 'Due polpette fatte a mano grigliate al momento - con due fette di bacon croccante e due fette di formaggio americano Kraft con pane morbido ai semi di sesamo.',
                'image' => 'baconcheeseburger.png',
                'price' => 12,90,
                'visible' => '1',
                'popular' => '1',
            ],
            [
                'restaurant_id' => 1,
                'plate_name' => 'Cheese Veggie Sandwich',
                'description' => 'Cipolle, funghi e peperoni verdi grigliati con formaggio fuso americano Kraft servito su pane dorato e tostato con lattuga e pomodori. Più una delle tue 16 guarnizioni preferite!',
                'image' => 'cheeseveggiesandwich.png',
                'price' => 7,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 1,
                'plate_name' => 'Kosher Style Hot Dog',
                'description' => 'L’hot dog nazionale ebraico di sola carne di manzo è spaccato e grigliato longitudinalmente per un esterno caramellato.',
                'image' => 'kosherstylehotdog.png',
                'price' => 8,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 2,
                'plate_name' => 'Bowl Classic',
                'description' => 'riso, salmone, edamame, avocado, sesamo, alghe nori e salsa unaghi',
                'image' => 'bowlclassic.png',
                'price' => 9,90,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 2,
                'plate_name' => 'Bowl Salmon Anaua',
                'description' => 'riso, salmone griglia, edamame, sesamo e salsa teriyaki',
                'image' => 'bowlsalmonanaua.png',
                'price' => 11,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 2,
                'plate_name' => 'Bowl Tonno Hawa',
                'description' => 'riso, spicy tonno, jalapeño, avocado, cetrioli, carote, sesamo, tobiko e spicy maionese',
                'image' => 'bowltonnohawa.png',
                'price' => 11,90,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 2,
                'plate_name' => 'Bowl White Fish',
                'description' => 'riso, spigola, mango, avocado, edamame, sesamo, alghe nori e ponzu',
                'image' => 'bowlwhitefish.png',
                'price' => 10,90,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 2,
                'plate_name' => 'Edamame',
                'description' => 'Fagioli di soia bolliti.',
                'image' => 'edamame.png',
                'price' => 3,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 2,
                'plate_name' => 'Ebi gyoza',
                'description' => 'Ravioli di gamberetti al vapore.',
                'image' => 'ebygyoza.png',
                'price' => 3,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 3,
                'plate_name' => 'Riso Cantonese',
                'description' => 'Riso con prosciutto, piselli e frittata.',
                'image' => 'risocantonese.png',
                'price' => 4,20,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 3,
                'plate_name' => 'Noodles',
                'description' => 'Noodles di riso con mix di verdure & uovo (carote, zucchine,cavolo).',
                'image' => 'noodles.png',
                'price' => 5,20,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 3,
                'plate_name' => 'Ravioli di Manzo',
                'description' => 'Ravioli cotti al vapore farciti con mix di verdure e manzo.',
                'image' => 'raviolidimanzo.png',
                'price' => 3,5,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 3,
                'plate_name' => 'Involtini Primavera',
                'description' => 'Involtini fritti con ripieno di verdure miste, preparati a mano dai nostri cuochi il tutto accompagnato da salsa agrodolce a parte.',
                'image' => 'involtiniprimavera.png',
                'price' => 3,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 3,
                'plate_name' => 'Pollo con Mandorle',
                'description' => 'Bocconcini di pollo saltato in padella con mandorle.',
                'image' => 'polloconmandorle.png',
                'price' => 4,10,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 4,
                'plate_name' => 'Spaghetti alla carbonara',
                'description' => 'Spaghetti alla chitarra freschi, con guanciale pecorino e uova.',
                'image' => 'spaghettiallacarbonara.png',
                'price' => 10,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 4,
                'plate_name' => 'Paccheri alla Giannino',
                'description' => 'Paccheri con bufala, pachino e basilico.',
                'image' => 'paccheriallagiannino.png',
                'price' => 9,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 4,
                'plate_name' => 'Gnocchi ai 4 formaggi',
                'description' => 'Gnocchi di patate fatti in casa, con toma, gorgonzola, fontina e parmigiano.',
                'image' => 'gnocchiai4formaggi.png',
                'price' => 8,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 4,
                'plate_name' => 'Arrosticini',
                'description' => 'Spiedini di agnello cotti alla griglia.',
                'image' => 'arrosticini.png',
                'price' => 5,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 4,
                'plate_name' => 'Tagliata con rucola',
                'description' => 'Tagliata di manzo cotta alla brace con rucola.',
                'image' => 'tagliataconrucola.png',
                'price' => 15,50,
                'visible' => '1',
                'popular' => '0',
            ], /* update img giordano */
            [
                'restaurant_id' => 5,
                'plate_name' => 'Nachos Blancos',
                'description' => 'Chips di mais della casa con formaggio fondente.',
                'image' => 'nachosblancos.png',
                'price' => 6,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 5,
                'plate_name' => 'Quesadillas Marrana',
                'description' => '2 tortillas di farina alla piastra con ripieno di porchetta, formaggio, pomodoro accompagnate da tostadas de mais con insalata.',
                'image' => 'quesadillasmarrana.png',
                'price' => 9,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 5,
                'plate_name' => 'Frittura Centenario',
                'description' => 'Gustosi anelli di cipolla dolce dorati e bastoncini di mozzarella fritti accompagnati da tostada de mais con insalata.',
                'image' => 'fritturacentenario.png',
                'price' => 10,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 5,
                'plate_name' => 'Alitas de pollo doradas',
                'description' => 'La Specialità della Casa: alette di pollo impanate accompagnati da tostada de mais con insalata.',
                'image' => 'alitasdepollodoradas.png',
                'price' => 11,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 5,
                'plate_name' => 'Barbecue Ribs',
                'description' => 'Tipico piatto Ranchero…costine di maiale(10 dita)cotte al forno in salsa BBQ e patatine fritte.',
                'image' => 'barbecueribs.png',
                'price' => 16,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 5,
                'plate_name' => 'Mixed Grill Salsiccia',
                'description' => 'Salsiccia e salsicciotti alla griglia serviti con patatine fritte.',
                'image' => 'mixedgrillsalsiccia.png',
                'price' => 12,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 6,
                'plate_name' => 'Tonno Vitellato',
                'description' => 'Filetto di tonno con salsa di vitello e maionese di bottarga.',
                'image' => 'tonnovitellato.png',
                'price' => 19,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 6,
                'plate_name' => 'Spaghetti di gragnano con asparagi e calamari.',
                'description' => 'Spaghetti risottati in padella con i calamari e acqua al profumo di asparagi.',
                'image' => 'spaghettidigragnanoconasparagiecalamari.png',
                'price' => 23,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 6,
                'plate_name' => 'Salmone affumicato',
                'description' => 'Salmone cotto e affumicato a bassa temperatura con legno di cedro.',
                'image' => 'salmoneaffumicato.png',
                'price' => 29,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 7,
                'plate_name' => 'Regina', //pizza margherita
                'description' => 'Pomodoro, fiord di latte, olio EVO e basilico.',
                'image' => 'regina.png',
                'price' => 8,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 7,
                'plate_name' => 'Tris di montanare',
                'description' => 'Tre montanare: Classica, Parmigiana di melanzane, Crudo e Bufala',
                'image' => 'trisdimontanare.png',
                'price' => 9,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 7,
                'plate_name' => 'Vicaria',
                'description' => 'Pomodoro, fior di latte, salsiccia fresca(in cottura), olio EVO e basilico.',
                'image' => '',
                'price' => 9,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 7,
                'plate_name' => 'Pesto di basilico',
                'description' => 'Fior di latte, pesto fresco di basilico, pomodorini pachino, olio EVO e basilico.',
                'image' => 'pestodibasilico.png',
                'price' => 8,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 7,
                'plate_name' => 'Ripieno (calzone)',
                'description' => 'Pomodoro, fior di latte, ricotta fresca di bufala, salame, olio EVO basilico.',
                'image' => 'ripieno.png',
                'price' => 10,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 7,
                'plate_name' => 'Melanzane alla parmigiana',
                'description' => 'La classica ricetta delle Melanzane alla Parmigiana.',
                'image' => 'melanzaneallaparmigiana.png',
                'price' => 8,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 8,
                'plate_name' => 'Green Crust',
                'description' => 'Crostone con foglia verde saltata con maionese di cicoria e mandorle.',
                'image' => 'greencrust.png',
                'price' => 9,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 8,
                'plate_name' => 'Vellutata di stagione',
                'description' => 'Minestra vellutata con verdure di stagione.',
                'image' => 'vellutatadistagione.png',
                'price' => 9,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 8,
                'plate_name' => 'Hamburger di ceci',
                'description' => 'Hamburger di ceci homemade con contorno di avocado e zucchine.',
                'image' => 'hamburgerdiceci.png',
                'price' => 11,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 9,
                'plate_name' => 'Pepperoni Feast',
                'description' => 'Pepperoni, pepperoni and more pepperoni.',
                'image' => 'pepperonifeast.png',
                'price' => 8,99,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 9,
                'plate_name' => 'Chicken Supreme',
                'description' => 'Chicken breast, mushrooms, caramelised onions.',
                'image' => 'chickensupreme.png',
                'price' => 9,25,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 9,
                'plate_name' => 'BBQ Americano',
                'description' => 'Smoky BBq sauce, chicken breast, bacon, sweetcorn with a BBQ drizzle.',
                'image' => 'bbqamericano.png',
                'price' => 9,75,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 9,
                'plate_name' => 'Hawaiian',
                'description' => 'Ham and pineapple',
                'image' => 'hawaiian.png',
                'price' => 7,99,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 9,
                'plate_name' => 'Cheese triangles',
                'description' => 'Triangoli di mais con formaggio',
                'image' => 'cheesetriangles.png',
                'price' => 4,10,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 10,
                'plate_name' => 'Ebi yaki meshi',
                'description' => 'Riso saltato con gamberi, verdura e uova.',
                'image' => 'ebiyakimeshi.png',
                'price' => 6,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 10,
                'plate_name' => 'Ebi tempura',
                'description' => 'Gamberi fritti in salsa teriyaki.',
                'image' => 'ebitempura.png',
                'price' => 8,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 10,
                'plate_name' => 'Hosomaki Avocado',
                'description' => 'Riso, alga, avocado e sesamo.',
                'image' => 'hosomakiavocado.png',
                'price' => 3,50,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 10,
                'plate_name' => 'Temaki Sake',
                'description' => 'Salmone, philadephia, avocado e sesamo.',
                'image' => 'temakisake.png',
                'price' => 4,00,
                'visible' => '1',
                'popular' => '0',
            ],
            [
                'restaurant_id' => 10,
                'plate_name' => 'Gunkan Tobiko',
                'description' => 'Riso, uova di pesce volante.',
                'image' => 'gunkantobiko.png',
                'price' => 4,00,
                'visible' => '1',
                'popular' => '0',
            ],
        ];

        // ciclo su array di plates e inserimento di ogni elemento in plates table
        foreach($plates as $key => $plate){

            DB::table('plates') -> insert([
                'restaurant_id' => $plate['restaurant_id'],
                'plate_name' => $plate['plate_name'],
                'description' => $plate['description'],
                'image' => $plate['image'],
                'price' => $plate['price'],
                'visible' => $plate['visible'],
                'popular' => $plate['popular'],
            ]);
            
        }
    }
}
